# Cargar datos con pandas

In [1]:
import pandas as pd

In [61]:
coffe = pd.read_csv("./warmup-data/coffee.csv")

In [62]:
results = pd.read_parquet("./data/results.parquet")
bios = pd.read_csv("./data/bios.csv")

In [63]:
olympics_data = pd.read_excel("./data/olympics-data.xlsx")

# Acceso a los datos con pandas

In [5]:
coffe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [6]:
coffe.loc[0:3] #loc[filas, columnas], te entrega los datos segun la fila y columna que se pida

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [7]:
coffe.loc[0:]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [8]:
coffe.loc[5:8, ["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [9]:
coffe.iloc[0:5, [0,2]]  #solo usa indices, no strings. Obteniendo asi el mismo resultado de arriba. Tambien notar que para 
                        #iloc el indice superior no es inclusivo, mientras que en loc si lo es

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [10]:
#coffe.index = coffe.Day

In [11]:
#offe.index = coffe["Day"]

In [12]:
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [13]:
#coffe.loc["Monday":"Wednesday"] - con el indice modificado para que sean dias de la semana, esto muestra de lunes a miercoles
#coffe.loc[1:3,"Units Sold"] = 10 - modifica  las unidades dese el indice 1 al 3 con valor 10 en Units Sold

In [14]:
coffe.sort_values(["Units Sold","Coffee Type"], ascending=[0,1]) #descendente

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [15]:
for index,row in coffe.iterrows():  #otra forma de hacerlo, pero no es muy eficiente.
    print(index)
    print(row["Units Sold"])
    print("\n\n\n")

0
25




1
15




2
30




3
20




4
35




5
25




6
40




7
30




8
45




9
35




10
45




11
35




12
45




13
35

# Filtrar datos con Pandas

In [16]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [17]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [18]:
#filtra la altura de los atletas superiores a 215cm y solo muestra las 
#columnas 'name' y 'height_cm' junto con el indice.
#bios.loc[bios["height_cm"]> 215, ["name","height_cm"]] 
bios[bios["height_cm"]> 215][["name","height_cm"]]  #otra forma de escribirlo

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [19]:
bios[(bios["height_cm"]> 215) & (bios["born_country"] == 'USA')]  # '&' != 'and' (no son iguales)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [20]:
bios[bios['name'].str.contains('Keith|patrick', case =False)] #keith OR patrick. utiliza caracteres de busqueda similares a sql

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [21]:
bios.query('born_country == "USA" and born_city == "Seattle"') #tambien se pueden hacer query.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

# Añadir/Quitar columnas

In [22]:
#como vamos a hacer cambios para ejercitar y eventualmente se volvera a utilizar los datos de coffe, entonces se hara una copia
# de este y el original se dejara sin cambios
coffe_new = coffe.copy()
coffe_new['price'] = 4.99

In [23]:
import numpy as np
#se añaden precios a 2 tipos de cafe, como solo hay 2 tipos de cafe, entonces solo se menciona a 1 y cuando no se encuentre con Espresso
#el valor del cafe sera 5.99
coffe_new['new_price'] = np.where(coffe['Coffee Type']  == 'Espresso', 3.99, 5.99)

In [24]:
#se quita la fila con indice 0, pero no se cambian los datos. solo es para visualizacion
coffe_new.drop(0)

          Day Coffee Type  Units Sold  price  new_price
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [25]:
#coffe_new.drop(columns = ['price']) 
#mismo caso que el anterior, solo se quita para visualizar y no cambia los datos con los que se trabaja
coffe_new.drop(columns = ['price'], inplace = True) 
#de querer cambiar los valores de los datos cargados, se aplica un True que indica que efectivamente uno quiere hacer ese cambio

In [26]:
coffe_new

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [27]:
coffe_new['revenue'] = coffe_new['Units Sold'] * coffe_new['new_price']

In [28]:
coffe_new.rename(columns = {'new_price' : 'price' }, inplace = True)

In [29]:
coffe_new

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [30]:
bios_new = bios.copy()

In [31]:
#crea una columna con los primeros nombres
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [32]:
bios_new.query('first_name == "Jean" ')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
682,685,Jean Washer,1894-08-22,Berchem,Antwerpen,BEL,Belgium,NaN,NaN,1972-03-23,Jean
1301,1308,Jean Bassomben,1943-04-11,NaN,NaN,NaN,Cameroon,182.0,86.0,NaN,Jean
2998,3010,Jean Ces,1906-09-05,Béziers,Hérault,FRA,France,NaN,NaN,1969-12-25,Jean
3010,3022,Jean Despeaux,1915-10-22,Paris Xe,Paris,FRA,France,NaN,NaN,1989-05-25,Jean
...,...,...,...,...,...,...,...,...,...,...,...
137390,140744,Jean van der Westhuyzen,1998-12-09,Cape Town,Western Cape,RSA,Australia,184.0,NaN,NaN,Jean
138838,142265,Jean Carlos Caicedo,1995-01-10,Montecristi,Manabí,ECU,Ecuador,NaN,NaN,NaN,Jean
139464,142937,Jean Patry,1996-12-27,Montpellier,Hérault,FRA,France,NaN,NaN,NaN,Jean
139859,143349,Jean Paul Bredau,1999-06-27,Potsdam,Brandenburg,GER,Germany,190.0,82.0,NaN,Jean
142806,146429,Jean Spies,1989-11-27,NaN,NaN,NaN,South Africa,NaN,NaN,NaN,Jean

In [33]:
#crea columna de la fecha de nacimiento solo con el año
bios_new['born_year'] = pd.to_datetime(bios_new['born_date']).dt.year

In [34]:
bios_new[ 'born_datetime'] = pd.to_datetime(bios_new['born_date'], format="%Y-%m-%d")
#link con diferentes formas de usar '%' para los formatos de fechas:  https://www.bairesdev.com/tools/strftime/

In [35]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x:'Short' if x < 165 else('Average' if x < 185 else 'Tall'))
#lambda seria una funcion anonima que toma un parametro x
#crea una categoria y la clasifica como bajo, promedio o alto.

In [36]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'LightWeight'
    elif row['height_cm']< 175 and row['weight_kg'] <= 80:
        return 'Middleweight'
    else:
        return 'HeavyWeight'

bios_new['Category'] = bios.apply(categorize_athlete, axis=1) #1 es fila, 0 son columnas

In [37]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_year,born_datetime,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886.0,1886-12-12,Tall,HeavyWeight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969.0,1969-04-01,Average,HeavyWeight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898.0,1898-08-13,Average,HeavyWeight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895.0,1895-05-11,Average,LightWeight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878.0,1878-04-17,Tall,HeavyWeight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002.0,2002-01-30,Average,LightWeight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999.0,1999-09-20,Average,LightWeight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998.0,1998-05-08,Short,LightWeight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899.0,1899-05-19,Average,HeavyWeight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913.0,1913-07-15,Tall,HeavyWeight

In [38]:
bios_new.to_csv('./data/bios_new.csv', index= False) #para no guardar los indices por default como lo hace siempre pandas

# Fusionar y Concatenar Data

In [39]:
noc = pd.read_csv("./data/noc_regions.csv")

In [40]:
#esto mostrara un NOC_x y un NOC_y, esto se debe a que cuando se fusionan DataFrames en pandas y ambos tienen
#una columna con el mismo nombre, pandas las separa automaticamente con los prefixos 'x' e 'y'.
#el prefijo 'x' refiere al DataFrame de la izquierda, mientras que la 'y' refiere al de la derecha.
#en este x=bios , y=noc
bios_new = pd.merge(bios,noc, left_on='born_country', right_on='NOC', how='inner') #junta el pais de nacimiento con el pais representado

In [41]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)

In [42]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full'] ]
#muestra solo los paises que NO coinciden con el pais de nacimiento
#en este caso serian personas que nacieron en un pais pero despues representaron a otro en las olimpiadas
#NOC_x, NOC_y pueden ser distintos ya que al fusionar ambos DF, uno puede tener la data actualizada y otro no.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
14,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,MAR,Morocco,NaN
32,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,GBR,UK,NaN
33,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,GBR,UK,NaN
34,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110630,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN,TTO,Trinidad,Trinidad and Tobago
110632,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,RUS,Russia,NaN
110634,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
110635,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
110636,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN

In [43]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [44]:
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN

In [45]:
usa = bios[bios['born_country'] == 'USA'].copy()
gbr = bios[bios['born_country'] == 'GBR'].copy()

In [46]:
new_df = pd.concat([usa,gbr])  #se juntan ambas DF, una encima de la otra

# Manejando valores nulos

In [47]:
coffe_new.loc[[0,1], 'Units Sold'] = np.nan

In [48]:
coffe_new = coffe_new.fillna(coffe['Units Sold'].mean()) #se rellenan los valores nulos o vacios con el promedio de la columna 'Units Sold'

In [49]:
coffe_new['Units Sold'] = coffe_new['Units Sold'].interpolate().bfill().ffill()
#bfill = backward fill
#ffill = forward fill
#los metodos se ejecutan uno tras del otro, primero interpolando, luego rellena desde atras, y termina rellenando hacia adelante,
#asegurandose de que todos los valores nulos en Units Sold se completen

In [50]:
coffe_new.loc[[2,3], 'Units Sold'] = np.nan

In [51]:
coffe_new.dropna()
#quita TODA la fila que contenga nulos

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   32.857143   3.99    99.75
1      Monday       Latte   32.857143   5.99    89.85
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [52]:
coffe_new[coffe_new['Units Sold'].notna()]
#muestra lo que no contenga valores nulos. en este caso las filas con inices 2 y 3

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   32.857143   3.99    99.75
1      Monday       Latte   32.857143   5.99    89.85
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [53]:
coffe_new

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   32.857143   3.99    99.75
1      Monday       Latte   32.857143   5.99    89.85
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

# Aggregating Data

In [54]:
bios[bios['born_country'] == 'CHI']['born_region'].value_counts()
#CHILE EN LOS OLIMPICOS, VAMOOOOOH !!!!

born_region
Santiago Metropolitan               201
Valparaíso                           54
Biobío                               26
Los Lagos                            17
Maule                                16
Los Ríos                             15
Tarapacá                             14
Araucanía                            13
Antofagasta                          12
Coquimbo                              5
Magallanes and Antártica Chilena      3
Aisén                                 2
Atacama                               2
Arica and Parinacota                  1
Ñuble                                 1
Name: count, dtype: int64

In [55]:
coffe_new.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})
#agrupa los datos de coffee por tipo de cafe y dia, calculando para Units sold la suma y price el promedio

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Monday      32.857143   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday      0.000000   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   5.99
            Monday      32.857143   5.99
            Saturday    35.000000   5.99
            Sunday      35.000000   5.99
            Thursday    30.000000   5.99
            Tuesday      0.000000   5.99
            Wednesday   25.000000   5.99

In [56]:
pivot = coffe_new.pivot(columns = 'Coffee Type', index= 'Day', values='revenue')
#pivot transforma filas en columnas. agrega data basada en indices especificos y agrupacion de columnas
#tomas los valores unicos de especificados de 'columns' y las convierte en nuevos encabezados de columnas
#usa los valores del parametro 'index' como filas nuevas
#rellena las celdas intersectadas con valores de el paramtro 'values'

#ej
#Original "long" format:
#Day    Coffee Type    Revenue
#Mon    Espresso      100
#Mon    Latte         150
#Tue    Espresso      120
#Tue    Latte         180

#After pivot - "wide" format:
#Day    Espresso    Latte
#Mon    100         150
#Tue    120         180

In [57]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [58]:
bios_new['born_date'] = pd.to_datetime(bios_new['born_date'])
bios_new['month_born'] = bios_new['born_date'].dt.month
bios_new['year_born'] = bios_new['born_date'].dt.year
bios_new.groupby([bios_new['year_born'], bios_new['month_born']])['name'].count().reset_index().sort_values('name', ascending = False)

      year_born  month_born  name
1609     1985.0         3.0   203
1619     1986.0         1.0   197
1607     1985.0         1.0   193
1667     1990.0         1.0   188
1669     1990.0         3.0   184
...         ...         ...   ...
7        1840.0         5.0     1
5        1838.0         1.0     1
4        1837.0        12.0     1
3        1836.0         3.0     1
0        1828.0        10.0     1

[1869 rows x 3 columns]

# Funcionalidad Avanzada

In [59]:
#algunas fucnciones: .shift(), .rank(), .rolling(), .cumsum()
coffe_new['yesterday_revenue'] = coffe_new['revenue'].shift(2)
#se usa shift(2) porque el dataset va de 2 en 2 debido a los tipos de cafe

In [64]:
coffe_new['pct_change'] = coffe_new['revenue'] / coffe_new['yesterday_revenue'] * 100

In [65]:
coffe_new

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,32.857143,3.99,99.75,NaN,NaN
1,Monday,Latte,32.857143,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,NaN,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,NaN,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

In [69]:
bios_new['height_rank'] = bios_new['height_cm'].rank(ascending=False) #compara la estatura de todos y les da un rating desde el mas alto al mas bajo

In [70]:
bios_new.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes,month_born,year_born,height_rank
64496,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,CHN,China,NaN,9.0,1980.0,1.0
4070,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,USA,USA,NaN,2.0,1952.0,2.5
5027,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,LTU,Lithuania,NaN,12.0,1964.0,2.5
3975,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,GER,Germany,NaN,1.0,1963.0,5.0
64501,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,ESP,Spain,NaN,11.0,1975.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110629,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN,RUS,Russia,NaN,4.0,1996.0,NaN
110630,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN,TTO,Trinidad,Trinidad and Tobago,7.0,2001.0,NaN
110631,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,CUB,Cuba,NaN,4.0,1927.0,NaN
110632,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,RUS,Russia,NaN,8.0,1998.0,NaN
110638,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN,7.0,1913.0,NaN

In [76]:
coffe_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Day                 14 non-null     str
 1   Coffee Type         14 non-null     str
 2   Units Sold          12 non-null     float64
 3   price               14 non-null     float64
 4   revenue             14 non-null     float64
 5   yesterday_revenue   12 non-null     float64
 6   pct_change          12 non-null     float64
 7   cumulative_revenue  14 non-null     float64
dtypes: float64(6), str(2)
memory usage: 1.2 KB

In [74]:
coffe_new['cumulative_revenue'] = coffe_new['revenue'].cumsum()
#suma todos los ingresos y los va acumulando sucesivamente.

coffe_new

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,32.857143,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,32.857143,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,NaN,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,NaN,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.40

In [78]:
latte = coffe_new[coffe_new['Coffee Type'] == 'Latte' ].copy()
latte['3day'] = latte['Units Sold'].rolling(3).sum()

#ej:
#**Example with `rolling(3).sum()`:**
#- If you have data: [10, 20, 30, 40, 50]
#- Position 1: NaN (not enough previous values)
#- Position 2: NaN (still not enough previous values)  
#- Position 3: 10 + 20 + 30 = 60
#- Position 4: 20 + 30 + 40 = 90
#- Position 5: 30 + 40 + 50 = 120

#The rolling method is commonly used for:
#- Moving averages
#- Trend analysis
#- Smoothing noisy data
#- Time series analysis

latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,32.857143,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,NaN,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5,NaN
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,NaN
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,90.0
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.0
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.0

In [84]:
results_numpy = pd.read_csv('./data/results.csv')
results_arrow = pd.read_csv('./data/results.csv', engine= 'pyarrow', dtype_backend= 'pyarrow')

In [85]:
results_arrow.info()
results_numpy.info()
#en el ejemplo del video, la persona muestra las diferencias entre un 'antiguo' y un 'nuevo' formato para cargar los datos donde en vez de strings
# se ocupan objects, pero en este caso tenemos la version 3.0.3 de pndas donde se puede observar que en ambas situaciones nos arroja strings

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  double[pyarrow]
 1   type        305807 non-null  string[pyarrow]
 2   discipline  308407 non-null  string[pyarrow]
 3   event       308408 non-null  string[pyarrow]
 4   as          308408 non-null  string[pyarrow]
 5   athlete_id  308408 non-null  int64[pyarrow]
 6   noc         308407 non-null  string[pyarrow]
 7   team        121714 non-null  string[pyarrow]
 8   place       283193 non-null  double[pyarrow]
 9   tied        308408 non-null  bool[pyarrow]
 10  medal       44139 non-null   string[pyarrow]
dtypes: bool[pyarrow](1), double[pyarrow](2), int64[pyarrow](1), string[pyarrow](7)
memory usage: 37.5 MB
<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  str
 2   discipline  308407 non-null  str
 3   event       308408 non-null  str
 4   as          308408 non-null  str
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  str
 7   team        121714 non-null  str
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   str
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.0 MB

In [86]:
pd.__version__

'3.0.3'